# Asset placement helpers — invoked via blender-mcp execute_blender_code
#
# Usage from Claude:
#   - Load a .glb generated by Tripo P1 / Trellis 2
#   - Position, rotate, scale according to plan.json
#   - Tag for the iteration loop so we know what's been imported

import bpy
import os
from mathutils import Vector

def import_glb(filepath, name=None, position=(0, 0, 0), rotation_z_deg=0, scale=1.0, tag=None):
    """
    Import a single GLB. Returns the imported root object.

    - position: (x, y, z) world coords
    - rotation_z_deg: yaw rotation in degrees
    - scale: uniform scale factor
    - tag: optional string stored in obj["world_builder_tag"] for loop tracking
    """
    if not os.path.exists(filepath):
        raise FileNotFoundError(filepath)

    # Track what's selected before import so we can find the new objects
    before = set(bpy.context.scene.objects)
    bpy.ops.import_scene.gltf(filepath=filepath)
    new_objs = [o for o in bpy.context.scene.objects if o not in before]
    if not new_objs:
        raise RuntimeError(f"No objects imported from {filepath}")

    # Pick the root (highest-level parent of the new objects)
    roots = [o for o in new_objs if o.parent is None or o.parent not in new_objs]
    root = roots[0] if roots else new_objs[0]

    if name:
        root.name = name
    root.location = Vector(position)
    root.rotation_euler[2] = rotation_z_deg * 0.017453292519943295  # deg → rad
    root.scale = (scale, scale, scale)
    if tag:
        root["world_builder_tag"] = tag

    return root


def list_imported_assets():
    """Return all objects tagged by the loop (so Claude knows what's already in the scene)."""
    return [
        {
            "name": o.name,
            "tag": o.get("world_builder_tag"),
            "location": list(o.location),
            "scale": list(o.scale),
            "rotation_z_deg": o.rotation_euler[2] * 57.29577951308232,
        }
        for o in bpy.context.scene.objects
        if o.get("world_builder_tag")
    ]


def reposition(tag, position=None, rotation_z_deg=None, scale=None):
    """Adjust an already-imported asset by tag. Used by the judge step."""
    for o in bpy.context.scene.objects:
        if o.get("world_builder_tag") == tag:
            if position is not None:
                o.location = Vector(position)
            if rotation_z_deg is not None:
                o.rotation_euler[2] = rotation_z_deg * 0.017453292519943295
            if scale is not None:
                o.scale = (scale, scale, scale)
            return True
    return False


def remove_by_tag(tag):
    """Delete an imported asset by tag. Used when the judge wants to swap."""
    to_delete = [o for o in bpy.context.scene.objects if o.get("world_builder_tag") == tag]
    bpy.ops.object.select_all(action="DESELECT")
    for o in to_delete:
        o.select_set(True)
    if to_delete:
        bpy.ops.object.delete(use_global=False)
    return len(to_delete)


def save_backup(filepath):
    """Save a backup .blend without changing the active filepath."""
    bpy.ops.wm.save_as_mainfile(filepath=filepath, copy=True, check_existing=False)
    return filepath
